[[headers]]
  for = "*.png, *.PNG, *.jpg, *.JPG, *.jpeg, *.JPEG"
  [headers.values]
	cache-control = '''
	max-age=31536000,
	public'''

# [[headers]]
#   for = "*.css"
#   [headers.values]
# 	cache-control = '''
# 	max-age=31536000,
# 	public'''

# [[headers]]
#   for = "*.js"
#   [headers.values]
# 	cache-control = '''
# 	max-age=31536000,
# 	public'''